CREATE TYPE "public"."ai_provider" AS ENUM('deepseek', 'claude', 'auto');--> statement-breakpoint
CREATE TYPE "public"."destination_type" AS ENUM('wordpress_cliente', 'sitio_propio');--> statement-breakpoint
CREATE TYPE "public"."job_status" AS ENUM('pendiente', 'generando', 'completado', 'error');--> statement-breakpoint
CREATE TYPE "public"."publication_status" AS ENUM('pendiente', 'publicada', 'error');--> statement-breakpoint
CREATE TYPE "public"."source_status" AS ENUM('activa', 'pausada', 'error');--> statement-breakpoint
CREATE TYPE "public"."source_type" AS ENUM('rss', 'api', 'url');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'moderador');--> statement-breakpoint
CREATE TYPE "public"."version_status" AS ENUM('borrador', 'en_revision', 'aprobada', 'rechazada', 'publicada');--> statement-breakpoint
CREATE TABLE "articles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source_id" uuid,
	"url_original" text NOT NULL,
	"autor" text,
	"titulo" text,
	"contenido" text,
	"hash_contenido" text,
	"snapshot_original" text,
	"fecha_original" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid,
	"accion" text NOT NULL,
	"entidad" text NOT NULL,
	"entidad_id" text,
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "destinations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tipo" "destination_type" NOT NULL,
	"nombre" text NOT NULL,
	"config_api" jsonb DEFAULT '{}'::jsonb,
	"credenciales_cifradas" text,
	"estado" "source_status" DEFAULT 'activa' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "publications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"version_id" uuid NOT NULL,
	"destination_id" uuid NOT NULL,
	"estado" "publication_status" DEFAULT 'pendiente' NOT NULL,
	"url_publicada" text,
	"external_id" text,
	"idempotency_key" text NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rewrite_jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"article_id" uuid NOT NULL,
	"n_versiones" integer DEFAULT 1 NOT NULL,
	"tono" text,
	"proveedor" "ai_provider" DEFAULT 'auto' NOT NULL,
	"estado" "job_status" DEFAULT 'pendiente' NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tipo" "source_type" NOT NULL,
	"url" text NOT NULL,
	"nombre" text,
	"config" jsonb DEFAULT '{}'::jsonb,
	"estado" "source_status" DEFAULT 'activa' NOT NULL,
	"last_check" timestamp with time zone,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"nombre" text,
	"rol" "user_role" DEFAULT 'moderador' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "versions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"article_id" uuid NOT NULL,
	"rewrite_job_id" uuid,
	"titulo" text,
	"contenido" text NOT NULL,
	"similarity_score" real,
	"proveedor" "ai_provider",
	"tokens_in" integer,
	"tokens_out" integer,
	"costo" numeric(10, 6),
	"estado" "version_status" DEFAULT 'borrador' NOT NULL,
	"editado_por" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "articles" ADD CONSTRAINT "articles_source_id_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."sources"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publications" ADD CONSTRAINT "publications_version_id_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publications" ADD CONSTRAINT "publications_destination_id_destinations_id_fk" FOREIGN KEY ("destination_id") REFERENCES "public"."destinations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rewrite_jobs" ADD CONSTRAINT "rewrite_jobs_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "versions" ADD CONSTRAINT "versions_article_id_articles_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "versions" ADD CONSTRAINT "versions_rewrite_job_id_rewrite_jobs_id_fk" FOREIGN KEY ("rewrite_job_id") REFERENCES "public"."rewrite_jobs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "versions" ADD CONSTRAINT "versions_editado_por_users_id_fk" FOREIGN KEY ("editado_por") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "articles_hash_idx" ON "articles" USING btree ("hash_contenido");--> statement-breakpoint
CREATE UNIQUE INDEX "publications_idempotency_idx" ON "publications" USING btree ("idempotency_key");